import type { ItemEntry, ItemCategory } from './types';

export const blockCategories: ItemCategory[] = [
  {
    key: 'building', label: '建筑方块', icon: '🧱',
    items: [
      { id: 'stone', name: '石头' }, { id: 'granite', name: '花岗岩' }, { id: 'polished_granite', name: '磨制花岗岩' },
      { id: 'diorite', name: '闪长岩' }, { id: 'polished_diorite', name: '磨制闪长岩' },
      { id: 'andesite', name: '安山岩' }, { id: 'polished_andesite', name: '磨制安山岩' },
      { id: 'cobblestone', name: '圆石' }, { id: 'mossy_cobblestone', name: '苔石' },
      { id: 'stone_bricks', name: '石砖' }, { id: 'mossy_stone_bricks', name: '苔石砖' },
      { id: 'cracked_stone_bricks', name: '裂纹石砖' }, { id: 'chiseled_stone_bricks', name: '雕纹石砖' },
      { id: 'deepslate', name: '深板岩' }, { id: 'cobbled_deepslate', name: '深板岩圆石' },
      { id: 'polished_deepslate', name: '磨制深板岩' }, { id: 'deepslate_bricks', name: '深板岩砖' },
      { id: 'cracked_deepslate_bricks', name: '裂纹深板岩砖' }, { id: 'deepslate_tiles', name: '深板岩瓦' },
      { id: 'cracked_deepslate_tiles', name: '裂纹深板岩瓦' }, { id: 'chiseled_deepslate', name: '雕纹深板岩' },
      { id: 'bricks', name: '红砖块' }, { id: 'sandstone', name: '砂岩' }, { id: 'cut_sandstone', name: '切制砂岩' },
      { id: 'chiseled_sandstone', name: '雕纹砂岩' }, { id: 'smooth_sandstone', name: '平滑砂岩' },
      { id: 'red_sandstone', name: '红砂岩' }, { id: 'cut_red_sandstone', name: '切制红砂岩' },
      { id: 'chiseled_red_sandstone', name: '雕纹红砂岩' }, { id: 'smooth_red_sandstone', name: '平滑红砂岩' },
      { id: 'prismarine', name: '海晶石' }, { id: 'prismarine_bricks', name: '海晶石砖' },
      { id: 'dark_prismarine', name: '暗海晶石' }, { id: 'nether_bricks', name: '下界砖块' },
      { id: 'red_nether_bricks', name: '红色下界砖块' }, { id: 'cracked_nether_bricks', name: '裂纹下界砖块' },
      { id: 'chiseled_nether_bricks', name: '雕纹下界砖块' }, { id: 'blackstone', name: '黑石' },
      { id: 'polished_blackstone', name: '磨制黑石' }, { id: 'gilded_blackstone', name: '镶金黑石' },
      { id: 'polished_blackstone_bricks', name: '磨制黑石砖' }, { id: 'cracked_polished_blackstone_bricks', name: '裂纹磨制黑石砖' },
      { id: 'chiseled_polished_blackstone', name: '雕纹磨制黑石' },
      { id: 'end_stone', name: '末地石' }, { id: 'end_stone_bricks', name: '末地石砖' },
      { id: 'purpur_block', name: '紫珀块' }, { id: 'purpur_pillar', name: '紫珀柱' },
      { id: 'quartz_block', name: '石英块' }, { id: 'chiseled_quartz_block', name: '雕纹石英块' },
      { id: 'quartz_pillar', name: '石英柱' }, { id: 'smooth_quartz', name: '平滑石英块' },
      { id: 'calcite', name: '方解石' }, { id: 'tuff', name: '凝灰岩' }, { id: 'dripstone_block', name: '滴水石块' },
      { id: 'amethyst_block', name: '紫水晶块' }, { id: 'basalt', name: '玄武岩' },
      { id: 'smooth_basalt', name: '平滑玄武岩' }, { id: 'obsidian', name: '黑曜石' },
      { id: 'crying_obsidian', name: '哭泣的黑曜石' }, { id: 'ancient_debris', name: '远古残骸' },
    ],
  },
  {
    key: 'wood', label: '木质方块', icon: '🪵',
    items: [
      { id: 'oak_log', name: '橡木原木' }, { id: 'oak_wood', name: '橡木' }, { id: 'stripped_oak_log', name: '去皮橡木原木' },
      { id: 'oak_planks', name: '橡木木板' }, { id: 'spruce_log', name: '云杉原木' }, { id: 'spruce_wood', name: '云杉木' },
      { id: 'spruce_planks', name: '云杉木板' }, { id: 'birch_log', name: '白桦原木' }, { id: 'birch_wood', name: '白桦木' },
      { id: 'birch_planks', name: '白桦木板' }, { id: 'jungle_log', name: '丛林原木' }, { id: 'jungle_wood', name: '丛林木' },
      { id: 'jungle_planks', name: '丛林木板' }, { id: 'acacia_log', name: '金合欢原木' }, { id: 'acacia_wood', name: '金合欢木' },
      { id: 'acacia_planks', name: '金合欢木板' }, { id: 'dark_oak_log', name: '深色橡木原木' },
      { id: 'dark_oak_wood', name: '深色橡木' }, { id: 'dark_oak_planks', name: '深色橡木木板' },
      { id: 'mangrove_log', name: '红树原木' }, { id: 'mangrove_planks', name: '红树木板' },
      { id: 'cherry_log', name: '樱花原木' }, { id: 'cherry_wood', name: '樱花木' }, { id: 'cherry_planks', name: '樱花木板' },
      { id: 'pale_oak_log', name: '苍白橡木原木' }, { id: 'pale_oak_planks', name: '苍白橡木木板' },
      { id: 'crimson_stem', name: '绯红菌柄' }, { id: 'crimson_hyphae', name: '绯红菌核' },
      { id: 'crimson_planks', name: '绯红木板' }, { id: 'warped_stem', name: '诡异菌柄' },
      { id: 'warped_hyphae', name: '诡异菌核' }, { id: 'warped_planks', name: '诡异木板' },
      { id: 'bamboo_block', name: '竹块' }, { id: 'bamboo_planks', name: '竹板' },
      { id: 'bamboo_mosaic', name: '竹马赛克' },
    ],
  },
  {
    key: 'ore', label: '矿石', icon: '💎',
    items: [
      { id: 'coal_ore', name: '煤矿石' }, { id: 'deepslate_coal_ore', name: '深层煤矿石' },
      { id: 'iron_ore', name: '铁矿石' }, { id: 'deepslate_iron_ore', name: '深层铁矿石' },
      { id: 'copper_ore', name: '铜矿石' }, { id: 'deepslate_copper_ore', name: '深层铜矿石' },
      { id: 'gold_ore', name: '金矿石' }, { id: 'deepslate_gold_ore', name: '深层金矿石' },
      { id: 'diamond_ore', name: '钻石矿石' }, { id: 'deepslate_diamond_ore', name: '深层钻石矿石' },
      { id: 'emerald_ore', name: '绿宝石矿石' }, { id: 'deepslate_emerald_ore', name: '深层绿宝石矿石' },
      { id: 'lapis_ore', name: '青金石矿石' }, { id: 'deepslate_lapis_ore', name: '深层青金石矿石' },
      { id: 'redstone_ore', name: '红石矿石' }, { id: 'deepslate_redstone_ore', name: '深层红石矿石' },
      { id: 'nether_quartz_ore', name: '下界石英矿石' }, { id: 'nether_gold_ore', name: '下界金矿石' },
      { id: 'coal_block', name: '煤炭块' }, { id: 'iron_block', name: '铁块' }, { id: 'gold_block', name: '金块' },
      { id: 'diamond_block', name: '钻石块' }, { id: 'emerald_block', name: '绿宝石块' },
      { id: 'netherite_block', name: '下界合金块' }, { id: 'copper_block', name: '铜块' },
      { id: 'lapis_block', name: '青金石块' }, { id: 'redstone_block', name: '红石块' },
    ],
  },
  {
    key: 'redstone', label: '红石', icon: '⚡',
    items: [
      { id: 'redstone_wire', name: '红石线' }, { id: 'redstone_torch', name: '红石火把' },
      { id: 'repeater', name: '红石中继器' }, { id: 'comparator', name: '红石比较器' },
      { id: 'observer', name: '侦测器' }, { id: 'piston', name: '活塞' }, { id: 'sticky_piston', name: '黏性活塞' },
      { id: 'dispenser', name: '发射器' }, { id: 'dropper', name: '投掷器' },
      { id: 'hopper', name: '漏斗' }, { id: 'daylight_detector', name: '阳光探测器' },
      { id: 'target', name: '标靶' }, { id: 'sculk_sensor', name: '幽匿感测体' },
      { id: 'calibrated_sculk_sensor', name: '校频幽匿感测体' },
      { id: 'tripwire_hook', name: '绊线钩' }, { id: 'note_block', name: '音符盒' },
      { id: 'lever', name: '拉杆' }, { id: 'stone_button', name: '石按钮' }, { id: 'oak_button', name: '橡木按钮' },
      { id: 'stone_pressure_plate', name: '石压力板' }, { id: 'oak_pressure_plate', name: '橡木压力板' },
      { id: 'light_weighted_pressure_plate', name: '轻质测重压力板' }, { id: 'heavy_weighted_pressure_plate', name: '重质测重压力板' },
      { id: 'activator_rail', name: '激活铁轨' }, { id: 'detector_rail', name: '探测铁轨' },
      { id: 'powered_rail', name: '动力铁轨' }, { id: 'rail', name: '铁轨' },
      { id: 'tnt', name: 'TNT' }, { id: 'trapped_chest', name: '陷阱箱' },
    ],
  },
  {
    key: 'decorative', label: '装饰方块', icon: '🏺',
    items: [
      { id: 'glass', name: '玻璃' }, { id: 'glass_pane', name: '玻璃板' },
      { id: 'tinted_glass', name: '遮光玻璃' },
      { id: 'white_stained_glass', name: '白色染色玻璃' }, { id: 'orange_stained_glass', name: '橙色染色玻璃' },
      { id: 'magenta_stained_glass', name: '品红色染色玻璃' }, { id: 'light_blue_stained_glass', name: '淡蓝色染色玻璃' },
      { id: 'yellow_stained_glass', name: '黄色染色玻璃' }, { id: 'lime_stained_glass', name: '黄绿色染色玻璃' },
      { id: 'pink_stained_glass', name: '粉红色染色玻璃' }, { id: 'gray_stained_glass', name: '灰色染色玻璃' },
      { id: 'light_gray_stained_glass', name: '淡灰色染色玻璃' }, { id: 'cyan_stained_glass', name: '青色染色玻璃' },
      { id: 'purple_stained_glass', name: '紫色染色玻璃' }, { id: 'blue_stained_glass', name: '蓝色染色玻璃' },
      { id: 'brown_stained_glass', name: '棕色染色玻璃' }, { id: 'green_stained_glass', name: '绿色染色玻璃' },
      { id: 'red_stained_glass', name: '红色染色玻璃' }, { id: 'black_stained_glass', name: '黑色染色玻璃' },
      { id: 'white_wool', name: '白色羊毛' }, { id: 'orange_wool', name: '橙色羊毛' },
      { id: 'magenta_wool', name: '品红色羊毛' }, { id: 'light_blue_wool', name: '淡蓝色羊毛' },
      { id: 'yellow_wool', name: '黄色羊毛' }, { id: 'lime_wool', name: '黄绿色羊毛' },
      { id: 'pink_wool', name: '粉红色羊毛' }, { id: 'gray_wool', name: '灰色羊毛' },
      { id: 'light_gray_wool', name: '淡灰色羊毛' }, { id: 'cyan_wool', name: '青色羊毛' },
      { id: 'purple_wool', name: '紫色羊毛' }, { id: 'blue_wool', name: '蓝色羊毛' },
      { id: 'brown_wool', name: '棕色羊毛' }, { id: 'green_wool', name: '绿色羊毛' },
      { id: 'red_wool', name: '红色羊毛' }, { id: 'black_wool', name: '黑色羊毛' },
      { id: 'white_concrete', name: '白色混凝土' }, { id: 'orange_concrete', name: '橙色混凝土' },
      { id: 'magenta_concrete', name: '品红色混凝土' }, { id: 'light_blue_concrete', name: '淡蓝色混凝土' },
      { id: 'yellow_concrete', name: '黄色混凝土' }, { id: 'lime_concrete', name: '黄绿色混凝土' },
      { id: 'pink_concrete', name: '粉红色混凝土' }, { id: 'gray_concrete', name: '灰色混凝土' },
      { id: 'light_gray_concrete', name: '淡灰色混凝土' }, { id: 'cyan_concrete', name: '青色混凝土' },
      { id: 'purple_concrete', name: '紫色混凝土' }, { id: 'blue_concrete', name: '蓝色混凝土' },
      { id: 'brown_concrete', name: '棕色混凝土' }, { id: 'green_concrete', name: '绿色混凝土' },
      { id: 'red_concrete', name: '红色混凝土' }, { id: 'black_concrete', name: '黑色混凝土' },
      { id: 'terracotta', name: '陶瓦' }, { id: 'white_terracotta', name: '白色陶瓦' },
      { id: 'white_glazed_terracotta', name: '白色带釉陶瓦' }, { id: 'black_glazed_terracotta', name: '黑色带釉陶瓦' },
      { id: 'sea_lantern', name: '海晶灯' }, { id: 'glowstone', name: '荧石' },
      { id: 'shroomlight', name: '菌光体' }, { id: 'froglight', name: '蛙明灯' },
      { id: 'lantern', name: '灯笼' }, { id: 'soul_lantern', name: '灵魂灯笼' },
      { id: 'torch', name: '火把' }, { id: 'soul_torch', name: '灵魂火把' },
      { id: 'candle', name: '蜡烛' }, { id: 'end_rod', name: '末地烛' },
      { id: 'chain', name: '锁链' },
    ],
  },
  {
    key: 'plant', label: '植物', icon: '🌿',
    items: [
      { id: 'grass_block', name: '草方块' }, { id: 'dirt', name: '泥土' }, { id: 'coarse_dirt', name: '砂土' },
      { id: 'podzol', name: '灰化土' }, { id: 'mycelium', name: '菌丝' }, { id: 'moss_block', name: '苔藓块' },
      { id: 'mud', name: '泥巴' }, { id: 'clay', name: '黏土' }, { id: 'farmland', name: '耕地' },
      { id: 'dirt_path', name: '土径' }, { id: 'gravel', name: '沙砾' }, { id: 'sand', name: '沙子' },
      { id: 'red_sand', name: '红沙' }, { id: 'ice', name: '冰' }, { id: 'packed_ice', name: '浮冰' },
      { id: 'blue_ice', name: '蓝冰' }, { id: 'snow_block', name: '雪块' },
      { id: 'oak_sapling', name: '橡树树苗' }, { id: 'spruce_sapling', name: '云杉树苗' },
      { id: 'birch_sapling', name: '白桦树苗' }, { id: 'jungle_sapling', name: '丛林树苗' },
      { id: 'acacia_sapling', name: '金合欢树苗' }, { id: 'dark_oak_sapling', name: '深色橡树苗' },
      { id: 'cherry_sapling', name: '樱花树苗' }, { id: 'mangrove_propagule', name: '红树胎生苗' },
      { id: 'oak_leaves', name: '橡树树叶' }, { id: 'spruce_leaves', name: '云杉树叶' },
      { id: 'birch_leaves', name: '白桦树叶' }, { id: 'jungle_leaves', name: '丛林树叶' },
      { id: 'acacia_leaves', name: '金合欢树叶' }, { id: 'dark_oak_leaves', name: '深色橡树树叶' },
      { id: 'cherry_leaves', name: '樱花树叶' }, { id: 'azalea_leaves', name: '杜鹃树叶' },
      { id: 'flowering_azalea_leaves', name: '盛开的杜鹃树叶' },
      { id: 'grass', name: '草' }, { id: 'tall_grass', name: '高草丛' }, { id: 'fern', name: '蕨' },
      { id: 'dandelion', name: '蒲公英' }, { id: 'poppy', name: '虞美人' }, { id: 'blue_orchid', name: '兰花' },
      { id: 'allium', name: '绒球葱' }, { id: 'azure_bluet', name: '蓝花美耳草' }, { id: 'cornflower', name: '矢车菊' },
      { id: 'lily_of_the_valley', name: '铃兰' }, { id: 'sunflower', name: '向日葵' },
      { id: 'lilac', name: '丁香' }, { id: 'rose_bush', name: '玫瑰丛' }, { id: 'peony', name: '牡丹' },
      { id: 'wither_rose', name: '凋零玫瑰' }, { id: 'torchflower', name: '火炬花' },
      { id: 'cactus', name: '仙人掌' }, { id: 'bamboo', name: '竹子' }, { id: 'sugar_cane', name: '甘蔗' },
      { id: 'brown_mushroom', name: '棕色蘑菇' }, { id: 'red_mushroom', name: '红色蘑菇' },
      { id: 'crimson_fungus', name: '绯红菌' }, { id: 'warped_fungus', name: '诡异菌' },
      { id: 'crimson_roots', name: '绯红菌索' }, { id: 'warped_roots', name: '诡异菌索' },
      { id: 'nether_sprouts', name: '下界苗' }, { id: 'weeping_vines', name: '垂泪藤' },
      { id: 'twisting_vines', name: '缠怨藤' }, { id: 'big_dripleaf', name: '大型垂滴叶' },
      { id: 'small_dripleaf', name: '小型垂滴叶' }, { id: 'glow_lichen', name: '发光地衣' },
      { id: 'hanging_roots', name: '垂根' }, { id: 'moss_carpet', name: '苔藓地毯' },
      { id: 'azalea', name: '杜鹃花丛' }, { id: 'flowering_azalea', name: '盛开的杜鹃花丛' },
      { id: 'spore_blossom', name: '孢子花' }, { id: 'pink_petals', name: '粉红色花簇' },
      { id: 'dead_bush', name: '枯萎的灌木' }, { id: 'bush', name: '灌木丛' },
    ],
  },
  {
    key: 'functional', label: '功能方块', icon: '⚙️',
    items: [
      { id: 'crafting_table', name: '工作台' }, { id: 'furnace', name: '熔炉' },
      { id: 'blast_furnace', name: '高炉' }, { id: 'smoker', name: '烟熏炉' },
      { id: 'brewing_stand', name: '酿造台' }, { id: 'cauldron', name: '炼药锅' },
      { id: 'anvil', name: '铁砧' }, { id: 'chipped_anvil', name: '开裂的铁砧' },
      { id: 'damaged_anvil', name: '损坏的铁砧' }, { id: 'enchanting_table', name: '附魔台' },
      { id: 'grindstone', name: '砂轮' }, { id: 'smithing_table', name: '锻造台' },
      { id: 'cartography_table', name: '制图台' }, { id: 'fletching_table', name: '制箭台' },
      { id: 'loom', name: '织布机' }, { id: 'stonecutter', name: '切石机' },
      { id: 'barrel', name: '木桶' }, { id: 'chest', name: '箱子' }, { id: 'ender_chest', name: '末影箱' },
      { id: 'shulker_box', name: '潜影盒' }, { id: 'white_shulker_box', name: '白色潜影盒' },
      { id: 'black_shulker_box', name: '黑色潜影盒' }, { id: 'blue_shulker_box', name: '蓝色潜影盒' },
      { id: 'brown_shulker_box', name: '棕色潜影盒' }, { id: 'cyan_shulker_box', name: '青色潜影盒' },
      { id: 'gray_shulker_box', name: '灰色潜影盒' }, { id: 'green_shulker_box', name: '绿色潜影盒' },
      { id: 'light_blue_shulker_box', name: '淡蓝色潜影盒' }, { id: 'light_gray_shulker_box', name: '淡灰色潜影盒' },
      { id: 'lime_shulker_box', name: '黄绿色潜影盒' }, { id: 'magenta_shulker_box', name: '品红色潜影盒' },
      { id: 'orange_shulker_box', name: '橙色潜影盒' }, { id: 'pink_shulker_box', name: '粉红色潜影盒' },
      { id: 'purple_shulker_box', name: '紫色潜影盒' }, { id: 'red_shulker_box', name: '红色潜影盒' },
      { id: 'yellow_shulker_box', name: '黄色潜影盒' },
      { id: 'beacon', name: '信标' }, { id: 'conduit', name: '潮涌核心' },
      { id: 'lodestone', name: '磁石' }, { id: 'respawn_anchor', name: '重生锚' },
      { id: 'bedrock', name: '基岩' }, { id: 'obsidian', name: '黑曜石' },
      { id: 'campfire', name: '营火' }, { id: 'soul_campfire', name: '灵魂营火' },
      { id: 'composter', name: '堆肥桶' }, { id: 'beehive', name: '蜂箱' }, { id: 'bee_nest', name: '蜂巢' },
      { id: 'scaffolding', name: '脚手架' }, { id: 'ladder', name: '梯子' },
      { id: 'snow', name: '雪' }, { id: 'cobweb', name: '蜘蛛网' },
      { id: 'bookshelf', name: '书架' }, { id: 'chiseled_bookshelf', name: '雕纹书架' },
      { id: 'jukebox', name: '唱片机' }, { id: 'bell', name: '钟' },
      { id: 'pointed_dripstone', name: '滴水石锥' }, { id: 'lightning_rod', name: '避雷针' },
    ],
  },
];

export const allBlocks: ItemEntry[] = blockCategories.flatMap(c => c.items);
export const totalBlockCount = allBlocks.length;
