export interface ItemEntry {
  id: string;
  name: string;
}

export interface ItemCategory {
  key: string;
  label: string;
  icon: string;
  items: ItemEntry[];
}

export const itemCategories: ItemCategory[] = [
  {
    key: 'food', label: '食物', icon: '🍎',
    items: [
      { id: 'glow_berries', name: '发光浆果' }, { id: 'sweet_berries', name: '甜浆果' },
      { id: 'apple', name: '苹果' }, { id: 'golden_apple', name: '金苹果' },
      { id: 'enchanted_golden_apple', name: '附魔金苹果' }, { id: 'melon_slice', name: '西瓜片' },
      { id: 'chorus_fruit', name: '紫颂果' }, { id: 'carrot', name: '胡萝卜' },
      { id: 'golden_carrot', name: '金胡萝卜' }, { id: 'potato', name: '马铃薯' },
      { id: 'baked_potato', name: '烤马铃薯' }, { id: 'poisonous_potato', name: '毒马铃薯' },
      { id: 'beetroot', name: '甜菜根' }, { id: 'dried_kelp', name: '干海带' },
      { id: 'beef', name: '生牛肉' }, { id: 'cooked_beef', name: '牛排' },
      { id: 'porkchop', name: '生猪排' }, { id: 'cooked_porkchop', name: '熟猪排' },
      { id: 'mutton', name: '生羊肉' }, { id: 'cooked_mutton', name: '熟羊肉' },
      { id: 'chicken', name: '生鸡肉' }, { id: 'cooked_chicken', name: '熟鸡肉' },
      { id: 'rabbit', name: '生兔肉' }, { id: 'cooked_rabbit', name: '熟兔肉' },
      { id: 'cod', name: '生鳕鱼' }, { id: 'cooked_cod', name: '熟鳕鱼' },
      { id: 'salmon', name: '生鲑鱼' }, { id: 'cooked_salmon', name: '熟鲑鱼' },
      { id: 'tropical_fish', name: '热带鱼' }, { id: 'pufferfish', name: '河豚' },
      { id: 'bread', name: '面包' }, { id: 'cookie', name: '曲奇' },
      { id: 'cake', name: '蛋糕' }, { id: 'pumpkin_pie', name: '南瓜派' },
      { id: 'rotten_flesh', name: '腐肉' }, { id: 'spider_eye', name: '蜘蛛眼' },
      { id: 'mushroom_stew', name: '蘑菇煲' }, { id: 'beetroot_soup', name: '甜菜汤' },
      { id: 'rabbit_stew', name: '兔肉煲' }, { id: 'suspicious_stew', name: '谜之炖菜' },
      { id: 'honey_bottle', name: '蜂蜜瓶' }, { id: 'ominous_bottle', name: '不祥之瓶' },
    ],
  },
  {
    key: 'potion', label: '药水', icon: '🧪',
    items: [
      { id: 'potion', name: '药水' }, { id: 'splash_potion', name: '喷溅药水' },
      { id: 'lingering_potion', name: '滞留药水' },
    ],
  },
  {
    key: 'tool', label: '工具', icon: '⛏️',
    items: [
      { id: 'wooden_shovel', name: '木锹' }, { id: 'stone_shovel', name: '石锹' },
      { id: 'copper_shovel', name: '铜锹' }, { id: 'iron_shovel', name: '铁锹' },
      { id: 'golden_shovel', name: '金锹' }, { id: 'diamond_shovel', name: '钻石锹' },
      { id: 'netherite_shovel', name: '下界合金锹' }, { id: 'wooden_pickaxe', name: '木镐' },
      { id: 'stone_pickaxe', name: '石镐' }, { id: 'copper_pickaxe', name: '铜镐' },
      { id: 'iron_pickaxe', name: '铁镐' }, { id: 'golden_pickaxe', name: '金镐' },
      { id: 'diamond_pickaxe', name: '钻石镐' }, { id: 'netherite_pickaxe', name: '下界合金镐' },
      { id: 'wooden_axe', name: '木斧' }, { id: 'stone_axe', name: '石斧' },
      { id: 'copper_axe', name: '铜斧' }, { id: 'iron_axe', name: '铁斧' },
      { id: 'golden_axe', name: '金斧' }, { id: 'diamond_axe', name: '钻石斧' },
      { id: 'netherite_axe', name: '下界合金斧' }, { id: 'wooden_hoe', name: '木锄' },
      { id: 'stone_hoe', name: '石锄' }, { id: 'copper_hoe', name: '铜锄' },
      { id: 'iron_hoe', name: '铁锄' }, { id: 'golden_hoe', name: '金锄' },
      { id: 'diamond_hoe', name: '钻石锄' }, { id: 'netherite_hoe', name: '下界合金锄' },
    ],
  },
  {
    key: 'weapon', label: '武器', icon: '⚔️',
    items: [
      { id: 'wooden_sword', name: '木剑' }, { id: 'stone_sword', name: '石剑' },
      { id: 'copper_sword', name: '铜剑' }, { id: 'iron_sword', name: '铁剑' },
      { id: 'golden_sword', name: '金剑' }, { id: 'diamond_sword', name: '钻石剑' },
      { id: 'netherite_sword', name: '下界合金剑' }, { id: 'trident', name: '三叉戟' },
      { id: 'mace', name: '重锤' }, { id: 'shield', name: '盾牌' },
      { id: 'bow', name: '弓' }, { id: 'crossbow', name: '弩' },
      { id: 'arrow', name: '箭' }, { id: 'spectral_arrow', name: '光灵箭' },
      { id: 'tipped_arrow', name: '药箭' }, { id: 'snowball', name: '雪球' },
      { id: 'egg', name: '鸡蛋' },
    ],
  },
  {
    key: 'armor', label: '盔甲', icon: '🛡️',
    items: [
      { id: 'leather_helmet', name: '皮革帽子' }, { id: 'leather_chestplate', name: '皮革外套' },
      { id: 'leather_leggings', name: '皮革裤子' }, { id: 'leather_boots', name: '皮革靴子' },
      { id: 'chainmail_helmet', name: '锁链头盔' }, { id: 'chainmail_chestplate', name: '锁链胸甲' },
      { id: 'chainmail_leggings', name: '锁链护腿' }, { id: 'chainmail_boots', name: '锁链靴子' },
      { id: 'copper_helmet', name: '铜头盔' }, { id: 'copper_chestplate', name: '铜胸甲' },
      { id: 'copper_leggings', name: '铜护腿' }, { id: 'copper_boots', name: '铜靴子' },
      { id: 'iron_helmet', name: '铁头盔' }, { id: 'iron_chestplate', name: '铁胸甲' },
      { id: 'iron_leggings', name: '铁护腿' }, { id: 'iron_boots', name: '铁靴子' },
      { id: 'golden_helmet', name: '金头盔' }, { id: 'golden_chestplate', name: '金胸甲' },
      { id: 'golden_leggings', name: '金护腿' }, { id: 'golden_boots', name: '金靴子' },
      { id: 'diamond_helmet', name: '钻石头盔' }, { id: 'diamond_chestplate', name: '钻石胸甲' },
      { id: 'diamond_leggings', name: '钻石护腿' }, { id: 'diamond_boots', name: '钻石靴子' },
      { id: 'netherite_helmet', name: '下界合金头盔' }, { id: 'netherite_chestplate', name: '下界合金胸甲' },
      { id: 'netherite_leggings', name: '下界合金护腿' }, { id: 'netherite_boots', name: '下界合金靴子' },
      { id: 'turtle_helmet', name: '海龟壳' },
    ],
  },
  {
    key: 'horse_armor', label: '马铠/宠物装备', icon: '🐴',
    items: [
      { id: 'leather_horse_armor', name: '皮革马铠' }, { id: 'copper_horse_armor', name: '铜马铠' },
      { id: 'iron_horse_armor', name: '铁马铠' }, { id: 'golden_horse_armor', name: '金马铠' },
      { id: 'diamond_horse_armor', name: '钻石马铠' }, { id: 'netherite_horse_armor', name: '下界合金马铠' },
      { id: 'wolf_armor', name: '狼铠' },
      { id: 'white_harness', name: '白色挽具' }, { id: 'orange_harness', name: '橙色挽具' },
      { id: 'magenta_harness', name: '品红色挽具' }, { id: 'light_blue_harness', name: '淡蓝色挽具' },
      { id: 'yellow_harness', name: '黄色挽具' }, { id: 'lime_harness', name: '黄绿色挽具' },
      { id: 'pink_harness', name: '粉红色挽具' }, { id: 'gray_harness', name: '灰色挽具' },
      { id: 'light_gray_harness', name: '淡灰色挽具' }, { id: 'cyan_harness', name: '青色挽具' },
      { id: 'purple_harness', name: '紫色挽具' }, { id: 'blue_harness', name: '蓝色挽具' },
      { id: 'brown_harness', name: '棕色挽具' }, { id: 'green_harness', name: '绿色挽具' },
      { id: 'red_harness', name: '红色挽具' }, { id: 'black_harness', name: '黑色挽具' },
    ],
  },
  {
    key: 'bucket', label: '桶', icon: '🪣',
    items: [
      { id: 'bucket', name: '铁桶' }, { id: 'water_bucket', name: '水桶' },
      { id: 'cod_bucket', name: '鳕鱼桶' }, { id: 'salmon_bucket', name: '鲑鱼桶' },
      { id: 'tropical_fish_bucket', name: '热带鱼桶' }, { id: 'pufferfish_bucket', name: '河豚桶' },
      { id: 'axolotl_bucket', name: '美西螈桶' }, { id: 'tadpole_bucket', name: '蝌蚪桶' },
      { id: 'sulfur_cube_bucket', name: '硫方怪桶' }, { id: 'lava_bucket', name: '熔岩桶' },
      { id: 'powder_snow_bucket', name: '细雪桶' }, { id: 'milk_bucket', name: '奶桶' },
    ],
  },
  {
    key: 'boat', label: '船', icon: '🛶',
    items: [
      { id: 'oak_boat', name: '橡木船' }, { id: 'oak_chest_boat', name: '橡木运输船' },
      { id: 'spruce_boat', name: '云杉木船' }, { id: 'spruce_chest_boat', name: '云杉木运输船' },
      { id: 'birch_boat', name: '白桦木船' }, { id: 'birch_chest_boat', name: '白桦木运输船' },
      { id: 'jungle_boat', name: '丛林木船' }, { id: 'jungle_chest_boat', name: '丛林木运输船' },
      { id: 'acacia_boat', name: '金合欢木船' }, { id: 'acacia_chest_boat', name: '金合欢木运输船' },
      { id: 'dark_oak_boat', name: '深色橡木船' }, { id: 'dark_oak_chest_boat', name: '深色橡木运输船' },
      { id: 'mangrove_boat', name: '红树木船' }, { id: 'mangrove_chest_boat', name: '红树木运输船' },
      { id: 'cherry_boat', name: '樱花木船' }, { id: 'cherry_chest_boat', name: '樱花木运输船' },
      { id: 'pale_oak_boat', name: '苍白橡木船' }, { id: 'pale_oak_chest_boat', name: '苍白橡木运输船' },
      { id: 'bamboo_raft', name: '竹筏' }, { id: 'bamboo_chest_raft', name: '运输竹筏' },
    ],
  },
  {
    key: 'minecart', label: '矿车', icon: '🚂',
    items: [
      { id: 'minecart', name: '矿车' }, { id: 'hopper_minecart', name: '漏斗矿车' },
      { id: 'chest_minecart', name: '运输矿车' }, { id: 'furnace_minecart', name: '动力矿车' },
      { id: 'tnt_minecart', name: 'TNT矿车' }, { id: 'command_block_minecart', name: '命令方块矿车' },
    ],
  },
  {
    key: 'music_disc', label: '音乐唱片', icon: '🎵',
    items: [
      { id: 'music_disc_13', name: '音乐唱片 13' }, { id: 'music_disc_cat', name: '音乐唱片 Cat' },
      { id: 'music_disc_blocks', name: '音乐唱片 Blocks' }, { id: 'music_disc_chirp', name: '音乐唱片 Chirp' },
      { id: 'music_disc_far', name: '音乐唱片 Far' }, { id: 'music_disc_mall', name: '音乐唱片 Mall' },
      { id: 'music_disc_mellohi', name: '音乐唱片 Mellohi' }, { id: 'music_disc_stal', name: '音乐唱片 Stal' },
      { id: 'music_disc_strad', name: '音乐唱片 Strad' }, { id: 'music_disc_ward', name: '音乐唱片 Ward' },
      { id: 'music_disc_11', name: '音乐唱片 11' }, { id: 'music_disc_wait', name: '音乐唱片 Wait' },
      { id: 'music_disc_otherside', name: '音乐唱片 Otherside' }, { id: 'music_disc_relic', name: '音乐唱片 Relic' },
      { id: 'music_disc_5', name: '音乐唱片 5' }, { id: 'music_disc_pigstep', name: '音乐唱片 Pigstep' },
      { id: 'music_disc_creator', name: '音乐唱片 Creator' }, { id: 'music_disc_creator_music_box', name: '音乐唱片 Creator(八音盒)' },
      { id: 'music_disc_precipice', name: '音乐唱片 Precipice' },
    ],
  },
  {
    key: 'utility', label: '实用物品', icon: '🧰',
    items: [
      { id: 'fishing_rod', name: '钓鱼竿' }, { id: 'flint_and_steel', name: '打火石' },
      { id: 'fire_charge', name: '火焰弹' }, { id: 'bone_meal', name: '骨粉' },
      { id: 'shears', name: '剪刀' }, { id: 'brush', name: '刷子' },
      { id: 'name_tag', name: '命名牌' }, { id: 'lead', name: '拴绳' },
      { id: 'compass', name: '指南针' }, { id: 'recovery_compass', name: '追溯指针' },
      { id: 'clock', name: '时钟' }, { id: 'spyglass', name: '望远镜' },
      { id: 'map', name: '空地图' }, { id: 'filled_map', name: '地图' },
      { id: 'writable_book', name: '书与笔' }, { id: 'wind_charge', name: '风弹' },
      { id: 'ender_pearl', name: '末影珍珠' }, { id: 'elytra', name: '鞘翅' },
      { id: 'firework_rocket', name: '烟花火箭' }, { id: 'saddle', name: '鞍' },
      { id: 'carrot_on_a_stick', name: '胡萝卜钓竿' }, { id: 'warped_fungus_on_a_stick', name: '诡异菌钓竿' },
      { id: 'goat_horn', name: '山羊角' }, { id: 'totem_of_undying', name: '不死图腾' },
      { id: 'debug_stick', name: '调试棒' }, { id: 'experience_bottle', name: '附魔之瓶' },
      { id: 'trial_key', name: '试炼钥匙' }, { id: 'ominous_trial_key', name: '不祥试炼钥匙' },
      { id: 'enchanted_book', name: '附魔书' },
    ],
  },
  {
    key: 'bundle', label: '收纳袋', icon: '🎒',
    items: [
      { id: 'bundle', name: '收纳袋' }, { id: 'white_bundle', name: '白色收纳袋' },
      { id: 'orange_bundle', name: '橙色收纳袋' }, { id: 'magenta_bundle', name: '品红色收纳袋' },
      { id: 'light_blue_bundle', name: '淡蓝色收纳袋' }, { id: 'yellow_bundle', name: '黄色收纳袋' },
      { id: 'lime_bundle', name: '黄绿色收纳袋' }, { id: 'pink_bundle', name: '粉红色收纳袋' },
      { id: 'gray_bundle', name: '灰色收纳袋' }, { id: 'light_gray_bundle', name: '淡灰色收纳袋' },
      { id: 'cyan_bundle', name: '青色收纳袋' }, { id: 'purple_bundle', name: '紫色收纳袋' },
      { id: 'blue_bundle', name: '蓝色收纳袋' }, { id: 'brown_bundle', name: '棕色收纳袋' },
      { id: 'green_bundle', name: '绿色收纳袋' }, { id: 'red_bundle', name: '红色收纳袋' },
      { id: 'black_bundle', name: '黑色收纳袋' },
    ],
  },
  {
    key: 'material', label: '材料', icon: '📦',
    items: [
      { id: 'nether_wart', name: '下界疣' }, { id: 'ender_eye', name: '末影之眼' },
      { id: 'redstone', name: '红石粉' }, { id: 'string', name: '线' },
      { id: 'coal', name: '煤炭' }, { id: 'charcoal', name: '木炭' },
      { id: 'raw_copper', name: '粗铜' }, { id: 'raw_iron', name: '粗铁' },
      { id: 'raw_gold', name: '粗金' }, { id: 'emerald', name: '绿宝石' },
      { id: 'lapis_lazuli', name: '青金石' }, { id: 'diamond', name: '钻石' },
      { id: 'quartz', name: '下界石英' }, { id: 'amethyst_shard', name: '紫水晶碎片' },
      { id: 'copper_ingot', name: '铜锭' }, { id: 'iron_ingot', name: '铁锭' },
      { id: 'gold_ingot', name: '金锭' }, { id: 'copper_nugget', name: '铜粒' },
      { id: 'iron_nugget', name: '铁粒' }, { id: 'gold_nugget', name: '金粒' },
      { id: 'netherite_scrap', name: '下界合金碎片' }, { id: 'netherite_ingot', name: '下界合金锭' },
      { id: 'stick', name: '木棍' }, { id: 'flint', name: '燧石' },
      { id: 'wheat', name: '小麦' }, { id: 'bone', name: '骨头' },
      { id: 'feather', name: '羽毛' }, { id: 'leather', name: '皮革' },
      { id: 'rabbit_hide', name: '兔子皮' }, { id: 'honeycomb', name: '蜜脾' },
      { id: 'resin_clump', name: '树脂团' }, { id: 'ink_sac', name: '墨囊' },
      { id: 'glow_ink_sac', name: '荧光墨囊' }, { id: 'turtle_scute', name: '海龟鳞甲' },
      { id: 'armadillo_scute', name: '犰狳鳞甲' }, { id: 'slime_ball', name: '黏液球' },
      { id: 'clay_ball', name: '黏土球' }, { id: 'prismarine_shard', name: '海晶碎片' },
      { id: 'prismarine_crystals', name: '海晶砂粒' }, { id: 'nautilus_shell', name: '鹦鹉螺壳' },
      { id: 'heart_of_the_sea', name: '海洋之心' }, { id: 'blaze_rod', name: '烈焰棒' },
      { id: 'breeze_rod', name: '旋风棒' }, { id: 'nether_star', name: '下界之星' },
      { id: 'shulker_shell', name: '潜影壳' }, { id: 'popped_chorus_fruit', name: '爆裂紫颂果' },
      { id: 'echo_shard', name: '回响碎片' }, { id: 'disc_fragment_5', name: '唱片残片' },
      { id: 'bowl', name: '碗' }, { id: 'brick', name: '红砖' },
      { id: 'nether_brick', name: '下界砖' }, { id: 'resin_brick', name: '树脂砖' },
      { id: 'paper', name: '纸' }, { id: 'book', name: '书' },
      { id: 'written_book', name: '成书' }, { id: 'knowledge_book', name: '知识之书' },
      { id: 'firework_star', name: '烟火之星' }, { id: 'glass_bottle', name: '玻璃瓶' },
      { id: 'glowstone_dust', name: '荧石粉' }, { id: 'gunpowder', name: '火药' },
      { id: 'dragon_breath', name: '龙息' }, { id: 'fermented_spider_eye', name: '发酵蛛眼' },
      { id: 'blaze_powder', name: '烈焰粉' }, { id: 'sugar', name: '糖' },
      { id: 'rabbit_foot', name: '兔子脚' }, { id: 'glistering_melon_slice', name: '闪烁的西瓜片' },
      { id: 'magma_cream', name: '岩浆膏' }, { id: 'ghast_tear', name: '恶魂之泪' },
      { id: 'phantom_membrane', name: '幻翼膜' },
    ],
  },
  {
    key: 'dye', label: '染料', icon: '🎨',
    items: [
      { id: 'white_dye', name: '白色染料' }, { id: 'orange_dye', name: '橙色染料' },
      { id: 'magenta_dye', name: '品红色染料' }, { id: 'light_blue_dye', name: '淡蓝色染料' },
      { id: 'yellow_dye', name: '黄色染料' }, { id: 'lime_dye', name: '黄绿色染料' },
      { id: 'pink_dye', name: '粉红色染料' }, { id: 'gray_dye', name: '灰色染料' },
      { id: 'light_gray_dye', name: '淡灰色染料' }, { id: 'cyan_dye', name: '青色染料' },
      { id: 'purple_dye', name: '紫色染料' }, { id: 'blue_dye', name: '蓝色染料' },
      { id: 'brown_dye', name: '棕色染料' }, { id: 'green_dye', name: '绿色染料' },
      { id: 'red_dye', name: '红色染料' }, { id: 'black_dye', name: '黑色染料' },
    ],
  },
  {
    key: 'banner_pattern', label: '旗帜图案', icon: '🏴',
    items: [
      { id: 'field_masoned_banner_pattern', name: '砖纹旗帜图案' },
      { id: 'bordure_indented_banner_pattern', name: '波纹边旗帜图案' },
      { id: 'flower_banner_pattern', name: '花朵盾徽旗帜图案' },
      { id: 'creeper_banner_pattern', name: '苦力怕盾徽旗帜图案' },
      { id: 'skull_banner_pattern', name: '头颅盾徽旗帜图案' },
      { id: 'mojang_banner_pattern', name: 'Mojang徽标旗帜图案' },
      { id: 'globe_banner_pattern', name: '地球旗帜图案' },
      { id: 'piglin_banner_pattern', name: '猪鼻旗帜图案' },
      { id: 'flow_banner_pattern', name: '涡流旗帜图案' },
      { id: 'guster_banner_pattern', name: '旋风旗帜图案' },
    ],
  },
  {
    key: 'pottery_sherd', label: '陶片', icon: '🏺',
    items: [
      { id: 'angler_pottery_sherd', name: '垂钓纹样陶片' }, { id: 'archer_pottery_sherd', name: '弓箭纹样陶片' },
      { id: 'arms_up_pottery_sherd', name: '举臂纹样陶片' }, { id: 'blade_pottery_sherd', name: '利刃纹样陶片' },
      { id: 'brewer_pottery_sherd', name: '佳酿纹样陶片' }, { id: 'burn_pottery_sherd', name: '烈焰纹样陶片' },
      { id: 'danger_pottery_sherd', name: '危机纹样陶片' }, { id: 'explorer_pottery_sherd', name: '探险纹样陶片' },
      { id: 'flow_pottery_sherd', name: '涡流纹样陶片' }, { id: 'friend_pottery_sherd', name: '挚友纹样陶片' },
      { id: 'guster_pottery_sherd', name: '旋风纹样陶片' }, { id: 'heart_pottery_sherd', name: '爱心纹样陶片' },
      { id: 'heartbreak_pottery_sherd', name: '心碎纹样陶片' }, { id: 'howl_pottery_sherd', name: '狼嚎纹样陶片' },
      { id: 'miner_pottery_sherd', name: '采矿纹样陶片' }, { id: 'mourner_pottery_sherd', name: '悲恸纹样陶片' },
      { id: 'plenty_pottery_sherd', name: '富饶纹样陶片' }, { id: 'prize_pottery_sherd', name: '珍宝纹样陶片' },
      { id: 'scrape_pottery_sherd', name: '刮削纹样陶片' }, { id: 'sheaf_pottery_sherd', name: '麦捆纹样陶片' },
      { id: 'shelter_pottery_sherd', name: '树荫纹样陶片' }, { id: 'skull_pottery_sherd', name: '头颅纹样陶片' },
      { id: 'snort_pottery_sherd', name: '嗅探纹样陶片' },
    ],
  },
  {
    key: 'smithing_template', label: '锻造模板', icon: '🔨',
    items: [
      { id: 'netherite_upgrade_smithing_template', name: '下界合金升级' },
      { id: 'sentry_armor_trim_smithing_template', name: '哨兵盔甲纹饰' },
      { id: 'vex_armor_trim_smithing_template', name: '恼鬼盔甲纹饰' },
      { id: 'wild_armor_trim_smithing_template', name: '荒野盔甲纹饰' },
      { id: 'coast_armor_trim_smithing_template', name: '海岸盔甲纹饰' },
      { id: 'dune_armor_trim_smithing_template', name: '沙丘盔甲纹饰' },
      { id: 'wayfinder_armor_trim_smithing_template', name: '向导盔甲纹饰' },
      { id: 'raiser_armor_trim_smithing_template', name: '牧民盔甲纹饰' },
      { id: 'shaper_armor_trim_smithing_template', name: '塑造盔甲纹饰' },
      { id: 'host_armor_trim_smithing_template', name: '雇主盔甲纹饰' },
      { id: 'ward_armor_trim_smithing_template', name: '监守盔甲纹饰' },
      { id: 'silence_armor_trim_smithing_template', name: '幽静盔甲纹饰' },
      { id: 'tide_armor_trim_smithing_template', name: '潮汐盔甲纹饰' },
      { id: 'snout_armor_trim_smithing_template', name: '猪鼻盔甲纹饰' },
      { id: 'rib_armor_trim_smithing_template', name: '肋骨盔甲纹饰' },
      { id: 'eye_armor_trim_smithing_template', name: '眼眸盔甲纹饰' },
      { id: 'spire_armor_trim_smithing_template', name: '尖塔盔甲纹饰' },
      { id: 'flow_armor_trim_smithing_template', name: '涡流盔甲纹饰' },
      { id: 'bolt_armor_trim_smithing_template', name: '镶铆盔甲纹饰' },
    ],
  },
  {
    key: 'decorative', label: '装饰品', icon: '🖼️',
    items: [
      { id: 'end_crystal', name: '末地水晶' }, { id: 'armor_stand', name: '盔甲架' },
      { id: 'item_frame', name: '物品展示框' }, { id: 'glow_item_frame', name: '荧光物品展示框' },
      { id: 'painting', name: '画' },
    ],
  },
  {
    key: 'spawn_egg', label: '刷怪蛋', icon: '🥚',
    items: [
      { id: 'chicken_spawn_egg', name: '鸡' }, { id: 'cow_spawn_egg', name: '牛' },
      { id: 'pig_spawn_egg', name: '猪' }, { id: 'sheep_spawn_egg', name: '绵羊' },
      { id: 'camel_spawn_egg', name: '骆驼' }, { id: 'donkey_spawn_egg', name: '驴' },
      { id: 'horse_spawn_egg', name: '马' }, { id: 'mule_spawn_egg', name: '骡' },
      { id: 'cat_spawn_egg', name: '猫' }, { id: 'parrot_spawn_egg', name: '鹦鹉' },
      { id: 'wolf_spawn_egg', name: '狼' }, { id: 'armadillo_spawn_egg', name: '犰狳' },
      { id: 'fox_spawn_egg', name: '狐狸' }, { id: 'goat_spawn_egg', name: '山羊' },
      { id: 'llama_spawn_egg', name: '羊驼' }, { id: 'ocelot_spawn_egg', name: '豹猫' },
      { id: 'panda_spawn_egg', name: '熊猫' }, { id: 'polar_bear_spawn_egg', name: '北极熊' },
      { id: 'rabbit_spawn_egg', name: '兔子' }, { id: 'axolotl_spawn_egg', name: '美西螈' },
      { id: 'dolphin_spawn_egg', name: '海豚' }, { id: 'frog_spawn_egg', name: '青蛙' },
      { id: 'glow_squid_spawn_egg', name: '发光鱿鱼' }, { id: 'pufferfish_spawn_egg', name: '河豚' },
      { id: 'salmon_spawn_egg', name: '鲑鱼' }, { id: 'squid_spawn_egg', name: '鱿鱼' },
      { id: 'tadpole_spawn_egg', name: '蝌蚪' }, { id: 'tropical_fish_spawn_egg', name: '热带鱼' },
      { id: 'turtle_spawn_egg', name: '海龟' }, { id: 'allay_spawn_egg', name: '悦灵' },
      { id: 'mooshroom_spawn_egg', name: '哞菇' }, { id: 'sniffer_spawn_egg', name: '嗅探兽' },
      { id: 'sulfur_cube_spawn_egg', name: '硫方怪' }, { id: 'iron_golem_spawn_egg', name: '铁傀儡' },
      { id: 'snow_golem_spawn_egg', name: '雪傀儡' }, { id: 'trader_llama_spawn_egg', name: '行商羊驼' },
      { id: 'villager_spawn_egg', name: '村民' }, { id: 'wandering_trader_spawn_egg', name: '流浪商人' },
      { id: 'bat_spawn_egg', name: '蝙蝠' }, { id: 'bee_spawn_egg', name: '蜜蜂' },
      { id: 'skeleton_spawn_egg', name: '骷髅' }, { id: 'stray_spawn_egg', name: '流浪者' },
      { id: 'wither_skeleton_spawn_egg', name: '凋灵骷髅' }, { id: 'spider_spawn_egg', name: '蜘蛛' },
      { id: 'cave_spider_spawn_egg', name: '洞穴蜘蛛' }, { id: 'zombie_spawn_egg', name: '僵尸' },
      { id: 'husk_spawn_egg', name: '尸壳' }, { id: 'drowned_spawn_egg', name: '溺尸' },
      { id: 'zombie_villager_spawn_egg', name: '僵尸村民' }, { id: 'creeper_spawn_egg', name: '苦力怕' },
      { id: 'bogged_spawn_egg', name: '沼骸' }, { id: 'breeze_spawn_egg', name: '旋风人' },
      { id: 'creaking_spawn_egg', name: '嘎枝' }, { id: 'enderman_spawn_egg', name: '末影人' },
      { id: 'endermite_spawn_egg', name: '末影螨' }, { id: 'shulker_spawn_egg', name: '潜影贝' },
      { id: 'slime_spawn_egg', name: '史莱姆' }, { id: 'magma_cube_spawn_egg', name: '岩浆怪' },
      { id: 'ghast_spawn_egg', name: '恶魂' }, { id: 'blaze_spawn_egg', name: '烈焰人' },
      { id: 'piglin_spawn_egg', name: '猪灵' }, { id: 'piglin_brute_spawn_egg', name: '猪灵蛮兵' },
      { id: 'hoglin_spawn_egg', name: '疣猪兽' }, { id: 'zoglin_spawn_egg', name: '僵尸疣猪兽' },
      { id: 'zombified_piglin_spawn_egg', name: '僵尸猪灵' }, { id: 'strider_spawn_egg', name: '炽足兽' },
      { id: 'phantom_spawn_egg', name: '幻翼' }, { id: 'guardian_spawn_egg', name: '守卫者' },
      { id: 'elder_guardian_spawn_egg', name: '远古守卫者' }, { id: 'silverfish_spawn_egg', name: '蠹虫' },
      { id: 'witch_spawn_egg', name: '女巫' }, { id: 'evoker_spawn_egg', name: '唤魔者' },
      { id: 'pillager_spawn_egg', name: '掠夺者' }, { id: 'ravager_spawn_egg', name: '劫掠兽' },
      { id: 'vex_spawn_egg', name: '恼鬼' }, { id: 'vindicator_spawn_egg', name: '卫道士' },
      { id: 'warden_spawn_egg', name: '监守者' }, { id: 'wither_spawn_egg', name: '凋灵' },
      { id: 'ender_dragon_spawn_egg', name: '末影龙' },
    ],
  },
];

/** 所有物品扁平列表，用于搜索 */
export const allItems: ItemEntry[] = itemCategories.flatMap(c => c.items);

/** 物品总数 */
export const totalItemCount = allItems.length;
